### ISSUE TITLE
Exception when printing Single Job

### ISSUE THREAD

**Issue by jrcasso** [jrcasso/StarburstAutomator#2]
Exception gets raised when attempting to print a single job instead of a range:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jcasso\Downloads\Applications\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:/Users/jcasso/Documents/Code/Python/Automator/AutomatorBeta/MainFrameBeta.py", line 57, in <lambda>
    command=lambda: print_jobs())
  File "C:/Users/jcasso/Documents/Code/Python/Automator/AutomatorBeta/MainFrameBeta.py", line 417, in print_jobs
    "Save trees!").format(job_info[0][0])
AttributeError: 'NoneType' object has no attribute 'format'
ERROR: execution aborted
```

If not aborted in time, this error causes the program to crash.

**Comment by jrcasso** [comment]
Resolution:

Missing parenthesis. Attempted to use .format on a that technically didn't have {} within it.
